add default laravel 7 project
BuildForSDG/Team-220-Backend pull request #4
Opened 2020-05-10 23:08 UTC by fabriceyopa

## Description
Add Laravel 7 project,

Just to be sure that is it the way to go

2020-05-11 00:04 UTC, WilChrist requested changes
@fabriceyopa Nice Job, sounds good. But please try to always have the PR checks proposed in the default template of github. Can you add that, please?

Please also link the issue this PR is resolving.

2020-05-11 00:08 UTC, WilChrist commented
For the next time please name your branches according to the coventions Andela suggest us here : https://docs.google.com/presentation/d/1hvnwv76gX98nAAgTxJp47CremzwPkfzDkXgejQGz2l0/edit?usp=sharing

2020-05-11 06:54 UTC, fabriceyopa commented
Ok, let me check that

2020-05-14 16:25 UTC, fabriceyopa commented
Please @WilChrist can you give me again the template for the pull request. And what about the next reviewer?

2020-05-14 16:32 UTC, WilChrist commented
@fabriceyopa that is (you can hae it by doing like if you want to create a new PR):

## Description
Please include a summary of the change and relevant motivation and context. 
List any dependencies that are required for this change.

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes #(issue number 1) #(issue number 2 if applicable)

## How Has This Been Tested?
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to see how your change affects other areas of the code etc.

## Screenshots (if applicable, else remove this line / section)


## Checklist:
<!--- Put an `x` in all the boxes that apply ! -->
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

2020-05-14 16:33 UTC, WilChrist commented
The next reviewer is @kouffen

2020-05-14 16:38 UTC, closed without merging

2020-05-17 01:11 UTC, kouffen commented on composer.json
> -  "name": "",
Here i think , we can fill the name of our app. so we can put "name : 'ImNotFoolJustSick'

2020-05-17 01:14 UTC, kouffen commented on composer.json
> -  "description": "",
for description , i propose this [ "description": "the backend part for the project ImNotFoolJustSick"

2020-05-17 01:24 UTC, kouffen reviewed
Nothing to Add, we can add features now. our base project is ready.